### ISSUE TITLE
quantsLabelStats.R -c option has no effect

### ISSUE THREAD

**Issue by cookpa** [ftdc-picsl/QuANTs#12]
This results in duplicate rows in QuANTs as we call the script twice with -c TRUE and -c FALSE.

As well as fixing this, it would be good to add a test for duplicate rows when the quants stats are gathered. This will guard against anyone accidentally duplicating data in the `stats/` directories.

**Comment by jeffduda** [comment]
Looks like some code was accidentally removed when I updated to use the JHU labels. Should be working correctly again. I also updated getQuants() to throw an error if repeat values are found. All time points from May 2019 and after will need to be rerun. Just for mindboggle using runMindboggleTimepoint with the --force flag to overwrite the existing csv files.
