### ISSUE TITLE
Cortical segmentation and thickness relationship

### ISSUE THREAD

**Issue by jeffduda** [ftdc-picsl/QuANTs#2]
1. Determine the conditions that results in a voxel labeled as cortex in the segmentation image having a zero value for cortical thickness
2. Decide if this may be used to clean/refine the segmentation image (possibly assign zero-thickness cortex voxels to a new class)

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/issues/580

Based on Nick's comment, I believe what's happening is that the mapping of the gray-white interface voxels to the exterior GM surface doesn't quite reach all the way.

I suppose it's also possible that the discrete sampling of the gray-white interface in voxel space could cause some voxels of GM to be missed. 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2836782/

**Comment by cookpa** [comment]
Decision: cortical labeled regions will be masked with (thickness > 0) and cortical volumes and thickness stats will be based on these masked labels.
