### ISSUE TITLE
Set ITK-SNAP version at run time

### ISSUE THREAD

**Issue by cookpa** [ftdc-picsl/QuANTs#7]
Maybe this is me but I'm finding the current ITK-SNAP to be unusably slow.

The code points to

```
  /share/apps/itksnap/itksnap-most-recent/bin/itksnap
```

which is a symlink to 

```
  /share/apps/itksnap/itksnap-3.8.0-beta-20181028-Linux-gcc64
```

The qt4 version

```
  /share/apps/itksnap/itksnap-3.8.0-beta-20181019-Linux-x86_64-qt4
```

works better for me. If it's not possible to set at run time it might be be better to point to a specific version that works for everyone, as `itksnap-most-recent` can be changed without notice.

**Comment by jeffduda** [comment]
I changed the default call to the qt4 version, I could add an option to quants_qc() to allow the user to pass a path to their preferred itksnap version and have the qt4 be the default.

**Comment by cookpa** [comment]
Maybe a consistent version is good, so I will close this unless anyone else has a problem with QT4.
