### ISSUE TITLE
as.wide in getQuants not working

### ISSUE THREAD

**Issue by caugolm** [ftdc-picsl/QuANTs#8]
Using the as.wide=T flag in getQuants() isn't working for me. It produces a matrix shaped correctly, but filled with "integer" factors for all region measurements.
It looks like the dcast() call in getQuants would prefer a function option, such as adding a ",mean" so it didn't produce the warning: "Aggregation function missing: defaulting to length." 
Something else might work better, as I could see potential for "mean" to result in unexpected behavior if the getQuants call doesn't specify for unique matches.

**Comment by jeffduda** [comment]
Can you send the command that caused that error. That means that two
different files contain the same measure, which shouldn't be the case.

**Comment by caugolm** [comment]
antsctpath <- "/data/grossman/pipedream2018/crossSectional/antsct/"
mbThickness = getQuants(path=antsctpath, id=idtps$INDDID, date=idtps$MRIDate, system="mindboggle", measure="thickness", metric="mean", as.wide=T)

**Comment by jeffduda** [comment]
i'll need the 'idtps' as well

**Comment by caugolm** [comment]
Ah, sorry-- I just emailed you a list

**Comment by jeffduda** [comment]
should work now that the stray file was removed
